openapi: 3.0.0
info:
  title: Green Screen API
  version: 1.0.0
servers:
  - url: https://gs-api.webdot.pro/api/v1
    description: Main (production) server
paths:
  /users:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role_id:
                  type: integer
      responses:
        '201':
          description: A user object.
        '422':
          description: Validation errors
